config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top' #rootパスでhomeに画面遷移
  devise_for :users
  resource :user, except: [:new, :create, :destroy]
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id #この書き方でrecipe_idとuser_idの組みが一通りしかないことができる
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :resipes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def already_favorited?(recipe) #いいねの判定をするためのメソッド(自作メソッド)
    self.favorites.exists?(recipe_id: recipe.id)
    #コードの説明
    #selfにはcurrent_userが入る。
    #crrent_userに結びついているいいねの中で、recipe_idが今いいねをしようとしているレシピのID recipe.idが存在するかを調べている
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource) #sign_inした時の画面遷移 #(resource)はresourceの書き方
    user_path
  end

  def after_sign_up_path_for(resource) #sign_upした時の画面遷移
    user_path
  end

  def after_sign_out_path_for(resource_or_sccope) #sign_outした時の画面遷移
    new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  #これで新規登録するときに名前も新規登録できるようになる。
end

#privateは、自分からしか見えないメソッド
#protectedは、一般の人から見られたくないが、仲間(クラスが同じオブジェクト)からは見えるメソッド

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
    #コードの説明
    #current_user.favorites.createは、current_userに結び付いているfavoriteを作成しているという意味
    #この書き方にすることでfavoriteテーブルのuser_idには自動的にログインしている人のcurrent_user.idが入る
    #(recipe_id: params[:recipe_id])この書き方で、いいねした記事のIDが必要になるからいいねした記事のIDを取得する
    #params[:recipe_id]を取ってきてrecipe_id:に格納している

    redirect_back(fallback_location: root_path)
    #コードの説明
    #これは、いいねしたときに前の画面に戻る。
    #一覧画面でいいねをしたら、一覧画面に戻って、詳細画面でいいねをしたら、詳細画面に戻るということをこのコードで行なっている。
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    #currnet_userに結びついているfacoritesをfind_byで持ってきてrecipe_idが上のコードで取ってきたrecipe.idを入れている
    #current_userには、user_idが入っていてrecipe_idには上のコードで取ってきた@recipeが入っている

    @favorite.destroy #上記で取ってきたものを削除している。
    redirect_back(fallback_location: root_path)
    #万が一前のURLが見つからなかったらroot_pathに遷移させる
    #これがなかったらエラーになるかもしれないから
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index] #index以外ログインユーザ出ないとアクセスできない
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id #ログインユーザーのIDを@recipeのuser_id(カラム)に代入
    if @recipe.save #もし保存されたら
      redirect_to recipe_path(@recipe),notice: '投稿に成功しました。' #リダイレクトで投稿したレシピの詳細画面へ遷移する
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user_id != current_user.id #編集する時、user_idとログインユーザーが等しくない(!=は等しくない)
      redirect_to recipes_path, alert: '不正なアクセスです。' #レシピの一覧画面に遷移
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "更新に成功しました。" #レシピの詳細画面に遷移
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path #レシピの一覧画面に遷移

    #@がついていないのはローカル変数だから
    #destroyアクションはビューには渡さないからつけていない
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報更新しました。'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'recipegram', root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if user_signed_in? %><%#ログインしている時で表示を変更するのにuser_sifned_in?を使用%>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'マイページ', user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to '新規投稿', new_recipe_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to '投稿一覧', recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>

    </nav>

    <% if flash[:notice] %><%#noticeは何かの通知に使用%>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %><%#alertは警告メッセージに使用%>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_errors.html.erb
<%#部分テンプレート%>
<% if recipe.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(recipe.errors.count, "error") %></h4><%#pluralizeヘルパーは英語専用のテキストヘルパー%>
    <%#pluralizeヘルパーは、最初の引数に整数があると、それに基づいて二番目の引数である英単語が複数形に変化したものが渡される%>
    <p><%= pluralize(recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%#部分テンプレート%>
<%= form_for recipe do |f| %>
  <div class="form-group">
    <label>レシピ名</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>作り方</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div>
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'errors', recipe: @recipe %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= render 'form', recipe: @recipe %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">レシピ名</th>
            <th scope="col">投稿者</th>
            <th scope="col">　</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do|recipe| %>
            <tr>
              <td><%= link_to recipe.title, recipe_path(recipe) %></td>
              <td><%= recipe.user.name %></td>
              <td>
                <% if current_user.already_favorited?(recipe) %><%#already_favorited?はuserモデルで作成したモデル%>
                  <%= link_to recipe_favorites_path(recipe), method: :delete do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to recipe_favorites_path(recipe), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
                <%= recipe.favorites.count %><%#これでレシピについたいいねを全て取ってくることができる。%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'errors', recipe: @recipe %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
        <%= render 'form', recipe: @recipe %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @recipe.title %></h5>
          <p class="card-text"><%= simple_format @recipe.body %></p><%#siple_formatは、改行が反映されるようになる。%>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @recipe.updated_at.strftime("%Y-%m-%d") %></small><%#strftime("%Y-%m-%d")この書き方は、時刻の表示をカスタマイズしている%>
          </p>
          <% if current_user.already_favorited?(@recipe) %>
            <%= link_to recipe_favorites_path(@recipe),method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to recipe_favorites_path(@recipe),method: :post do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <%= @recipe.favorites.count %>
          <% if @recipe.user == current_user %><%#レシピを投稿した人と、ログインしている人が同じならば編集と削除ボタンを表示させる%>
            <%= link_to '編集', edit_recipe_path(@recipe), class: "btn btn-success" %>
            <%= link_to '削除', recipe_path(@recipe), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4><%#pluralizeヘルパーは英語専用のテキストヘルパー%>
    <%#pluralizeヘルパーは、最初の引数に整数があると、それに基づいて二番目の引数である英単語が複数形に変化したものが渡される%>
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <%= form_for @user do |f|%>
        <div class="form-group">
          <label>ユーザー名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= current_user.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
          <%= link_to 'ユーザー編集',edit_user_path %><%#本来なら引数にIDを入れなければいけないが、今回はresouceでしているのでIDはいらない%>
        </div>
      </div>
    </div>
  </div>
</div>